### ISSUE TITLE
Simple Getting started has errors 

### ISSUE THREAD

**Issue by jasonfharris** [fastify/fastify-vite#55]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

3.0.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6 (Big Sur)

### Description

I followed the instructions in `https://fastify-vite.dev/quickstart/vue.html` but on trying to execute `node app.mjs` I get errors that `./symobls.js` is not found. Looking at the source in `node_modules/fastify-vite-vue/app.js` is looks like the code is:

```
const {
  kData,
  kPayload,
  kGlobal,
  kAPI,
  kIsomorphic,
  kFirstRender,
} = require('./symbols.js')
```

But there appears to be no file `symbols.js` in `node_modules/fastify-vite-vue`

### Steps to Reproduce

```
~/NodeProjects/ViteFastify ❱ mkdir simple
~/NodeProjects/ViteFastify ❱ cd simple
NodeProjects/ViteFastify/simple ❱ npm i fastify fastify-vite fastify-vite-vue --save

added 215 packages, and audited 216 packages in 19s

24 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

NodeProjects/ViteFastify/simple ❱ code ./../simple

<added the minimal files as per instructions>

NodeProjects/ViteFastify/simple ❱ node app.mjs                                                                                                 ⬢ v16.13.1 via 🅒 node-env-16.3.1
4:37:59 PM [vite] Error when evaluating SSR module @app/client.js:
Error: Cannot find module './symbols.js'
Require stack:
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/routing.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/vite/dist/node/chunks/dep-76613303.js:60126:20)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
4:37:59 PM [vite] Error when evaluating SSR module /Users/jason/NodeProjects/ViteFastify/simple/@app/entry/server.js:
Error: Cannot find module './symbols.js'
Require stack:
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/routing.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/vite/dist/node/chunks/dep-76613303.js:60126:20)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Cannot find module './symbols.js'
Require stack:
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js
- /Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/routing.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/vite/dist/node/chunks/dep-76613303.js:60126:20)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/app.js',
    '/Users/jason/NodeProjects/ViteFastify/simple/node_modules/fastify-vite-vue/routing.js'
  ]
}
```

### Expected Behavior

It to build and run correctly.

**Comment by galvez** [comment]
Hi @jasonfharris thank you so much for your report. 3.0.0 is still tagged as `alpha` on npm, can you try again fixing the release at 2.3.1, for both `fastify-vite` and the renderer adapter you're using?

In any case, new documentation and a proper beta release for v3 should arrive shortly, it's just that this is largely still a one-man operation (contributors very much welcome!), but it's getting there :)

**Comment by jasonfharris** [comment]
I found fastify while I was looking around at the state of javascript servers and I tried / played with:

 - Express
 - Koa
 - Fastify
 - [hyper-express](https://github.com/kartikk221/hyper-express)

After looking at the benchmarks etc Hyper-express seemed a lot faster. Also the hyper-express documentation was largely in sync with the code. Some of the things about fastify look quite compelling. But as I got hyper-express working I'll likely forge ahead with that for a while. If I get too stuck with it I think I will venture back to fastify (or Koa) in which case I'll look into this again!

**Comment by galvez** [comment]
You can't imagine my disappointment when I realized `hyper-express` had nothing to do with `hyper.rs` 😄 

Thanks for taking the time to try `fastify-vite`, it's definitely a work-in-progress and it's largely still a one-man operation, but hopefully things will change faster than you think.
