### ISSUE TITLE
Vue Minimal Boilerplate example error

### ISSUE THREAD

**Issue by erossdev** [fastify/fastify-vite#58]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.26.0

### Plugin version

2.3.1

### Node.js version

14.18.3

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0.1

### Description

I tried to follow the example [here](https://fastify-vite.dev/quickstart/vue.html) and am getting the following error

```
TypeError: __vite_ssr_import_1__.createMemoryHistory is not a function
    at createApp (@app/client.js:13:25)
    at async render (/Users/elliottross/projects/pulse/node_modules/.pnpm/fastify-vite-vue@2.3.1/node_modules/fastify-vite-vue/render.js:11:48)
    at async Object.<anonymous> (/Users/elliottross/projects/pulse/node_modules/.pnpm/fastify-vite-vue@2.3.1/node_modules/fastify-vite-vue/handler.js:21:25)
```

### Steps to Reproduce

1. Create app.mjs with what is in the minimal boilerplate example
2. Create views/index.vue with what is in the minimal boilerplate example
3. Run `node app.mjs`

### Expected Behavior

No error to show and page to render

**Comment by erossdev** [comment]
This seems to only be an issue because I am using PNPM. vue-router is a transitive dependency and I have old vue projects on my computer so PNPM was pulling in vue-router@3.x instead of 4.

For anyone using PNPM and seeing this issue I fixed it by just `pnpm add vue-router@4` in my project!
