### ISSUE TITLE
SPA mode results in `Cannot read properties of null`

### ISSUE THREAD

**Issue by jzillmann** [fastify/fastify-vite#91]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

3.0.0-beta.27

### Node.js version

16.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6 

### Description

When I enable SPA:
```
await server.register(FastifyVite, {
  dev: process.argv.includes("--dev"),
  root: import.meta.url,
  spa: true,
});
```

I'm getting 
```
TypeError: Cannot read properties of null (reading 'routes')
    at Vite.setup (/xxx/node_modules/fastify-vite/mode/development.js:57:35)
    at async Vite.ready (/xxx/node_modules/fastify-vite/index.js:32:55)
    at async file:///xxx/server.js:17:1
```

Also seems kind of obvious to me that this will always fail looking at `development.js`:
```
const loadClient = async () => {
    if (config.spa) {
      return null
    }
...
```
```
sync prepareClient (clientModule, scope, config) {
    if (!clientModule) {
      return null
    }
...
```
```
return { client, routes: client.routes, handler, errorHandler }
```

### Steps to Reproduce

Enable SPA:
```
await server.register(FastifyVite, {
  dev: process.argv.includes("--dev"),
  root: import.meta.url,
  spa: true,
});
```

### Expected Behavior

Either enabling SPA should work or there should be a clear instruction on how to set it up.
Would be nice to have a SPA example (preferable in Svelte).

**Comment by galvez** [comment]
Fixed for some time now.

**Comment by xezzon** [comment]
I can reproduce it in @fastify/vite 8.1.2.
